#add-mappings=true表示如果所有的controller都没有命中，则使用默认的静态资源处理器做匹配
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sr?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: kl13jk14
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource


#admin官方账号的用户名和密码
#admin:
#  email: pushkin
#  encryptPassword: 4QrcOUm6Wau+VuBX8g+IPg==

demo:
  spider:
    start:
      url: https://search.51job.com/list/addressCode,000000,0000,00,9,99,key,2,1.html?lang=c&postchannel=0000&workyear=99&cotype=99&degreefrom=99&jobterm=99&companysize=99&ord_field=0&dibiaoid=0&line=&welfare=

# 爬虫结果写入mysql/文件开关
spider:
  open:
    write:
      mysql: true
      file: false

elasticsearch:
  ip: 127.0.0.1:9200